### ISSUE TITLE
License for the code / calendar

### ISSUE THREAD

**Issue by hroncok** [fedora-python/python-release-schedule-ical#11]
Hello. I've noticed there there is no license stated (neither fo the code or for the generated calendar).

Would you please suggest a free software license that can be applied here before you get more contributors (it is a tad tricky once there are many, see for example [this issue](https://github.com/fedora-python/portingguide/issues/62))?

For the generated content, I suggest explicitly saying it "is placed in the public domain or under the CC0-1.0-Universal license, whichever is more permissive".

**Comment by hrnciar** [comment]
Hello, I have opened pull request. I would use CC0 for the calendar as well as code. Is that okay with you?
